import React from 'react';
import { CheckCircle, AlertTriangle, XCircle, Copy } from 'lucide-react';
import { AnalysisResult as AnalysisResultType } from '../types';

interface AnalysisResultProps {
  result: AnalysisResultType;
}

const AnalysisResult: React.FC<AnalysisResultProps> = ({ result }) => {
  const getVerdictIcon = () => {
    switch (result.verdict) {
      case 'suitable':
        return <CheckCircle className="w-8 h-8 text-green-600" />;
      case 'caution':
        return <AlertTriangle className="w-8 h-8 text-yellow-600" />;
      case 'unsuitable':
        return <XCircle className="w-8 h-8 text-red-600" />;
    }
  };

  const getVerdictColor = () => {
    switch (result.verdict) {
      case 'suitable':
        return 'bg-green-50 border-green-200';
      case 'caution':
        return 'bg-yellow-50 border-yellow-200';
      case 'unsuitable':
        return 'bg-red-50 border-red-200';
    }
  };

  const getVerdictText = () => {
    switch (result.verdict) {
      case 'suitable':
        return 'Suitable for Atopic Dermatitis';
      case 'caution':
        return 'Use with Caution';
      case 'unsuitable':
        return 'Not Recommended for Atopic Dermatitis';
    }
  };

  const copyReport = () => {
    const report = `
Eczema Checker Analysis Report
Verdict: ${getVerdictText()}

Flagged Ingredients:
${result.flaggedIngredients.map(ing => `- ${ing.name}: ${ing.reason}`).join('\n')}

Analysis based on:
- NEA Ecz-clusion List
- AAD Guidelines for Atopic Dermatitis Management
- Eichenfield LF, Tom WL. et al. "Guidelines of care for the management of atopic dermatitis: section 2. Management and treatment of atopic dermatitis with topical therapies." J Am Acad Dermatol. 2014 Jul;71(1):116-32.
- Sidbury R, Tom WL, et al. "Part 4: Guidelines of care for the management of atopic dermatitis. Part 4: Prevention of disease flares and use of adjunctive therapies and approaches. J Am Acad Dermatol. 2014: Jul;71(1);1218-33.

Generated by Eczema Checker
    `.trim();
    
    navigator.clipboard.writeText(report);
  };

  return (
    <div className="bg-white rounded-xl shadow-lg overflow-hidden">
      {/* Verdict Header */}
      <div className={`p-6 border-b-2 ${getVerdictColor()}`}>
        <div className="flex items-center justify-between">
          <div className="flex items-center">
            {getVerdictIcon()}
            <div className="ml-4 text-left">
              <h2 className="text-2xl font-bold text-gray-900">
                {getVerdictText()}
              </h2>
            </div>
          </div>
          <div className="flex gap-2">
            <button
              onClick={copyReport}
              className="p-2 text-gray-600 hover:text-gray-800 hover:bg-white rounded-lg transition-colors"
              title="Copy Report"
            >
              <Copy className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>

      <div className="p-6">
        {/* Flagged Ingredients */}
        {result.flaggedIngredients.length > 0 && (
          <div className="mb-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center text-left">
              <AlertTriangle className="w-5 h-5 text-yellow-600 mr-2" />
              Flagged Ingredients ({result.flaggedIngredients.length})
            </h3>
            <div className="space-y-3">
              {result.flaggedIngredients.map((ingredient, index) => (
                <div
                  key={index}
                  className={`p-4 rounded-lg border-l-4 ${
                    ingredient.status === 'avoid'
                      ? 'bg-red-50 border-red-400'
                      : 'bg-yellow-50 border-yellow-400'
                  }`}
                >
                  <div className="flex justify-between items-start">
                    <div className="flex-1 text-left">
                      <h4 className="font-semibold text-gray-900">
                        {ingredient.name}
                      </h4>
                      <p className="text-sm text-gray-600 mt-1">
                        INCI: {ingredient.inci}
                      </p>
                      <p className="text-sm text-gray-700 mt-2">
                        {ingredient.reason}
                      </p>
                    </div>
                    <div className="ml-4 flex flex-col items-end">
                      <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                        ingredient.status === 'avoid'
                          ? 'bg-red-100 text-red-800'
                          : 'bg-yellow-100 text-yellow-800'
                      }`}>
                        {ingredient.status === 'avoid' ? 'Avoid' : 'Caution'}
                      </span>
                      <span className="text-xs text-gray-500 mt-1">
                        {ingredient.source}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Safe Ingredients */}
        {result.safeIngredients.length > 0 && (
          <div className="mb-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center text-left">
              <CheckCircle className="w-5 h-5 text-green-600 mr-2" />
              Safe Ingredients ({result.safeIngredients.length})
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {result.safeIngredients.slice(0, 6).map((ingredient, index) => (
                <div
                  key={index}
                  className="p-3 bg-green-50 border border-green-200 rounded-lg text-left"
                >
                  <h4 className="font-medium text-gray-900 text-sm">
                    {ingredient.name}
                  </h4>
                  <p className="text-xs text-gray-600 mt-1">
                    {ingredient.reason}
                  </p>
                </div>
              ))}
              {result.safeIngredients.length > 6 && (
                <div className="p-3 bg-gray-50 border border-gray-200 rounded-lg flex items-center justify-center">
                  <span className="text-sm text-gray-600">
                    +{result.safeIngredients.length - 6} more safe ingredients
                  </span>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Disclaimer */}
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
          <p className="text-sm text-gray-600 text-left">
            <strong>Disclaimer:</strong> This analysis is based on NEA Ecz-clusion List and AAD guidelines for atopic dermatitis management. 
            Individual reactions may vary. Always patch test new products and consult with a dermatologist 
            for personalized advice. This tool is not a substitute for professional medical advice.
          </p>
        </div>
      </div>
    </div>
  );
};

export default AnalysisResult;
